/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sourcecode;

import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
/**
 *
 * Pengembang: Ariyal Zarhan Ikhlas Haryanto / XI RPL 2 / SMK Negeri 5 Kota Bekasi
 */
public class FormPembayaran extends javax.swing.JFrame {
 Koneksi koneksi = new Koneksi();

    public void loadData()
    {
        try{
            Connection c = Koneksi.getKoneksi();
            Statement s = c.createStatement();
            
            String sql = "SELECT * FROM biaya_bimbel_pendaftar";
            ResultSet r = s.executeQuery(sql);
            
            while(r.next()){
                Object[] o = new Object[8];
                o [0] = r.getString("id");
                o [1] = r.getString("nama_pendaftar");
                o [2] = r.getString("lama_bimbingan");
                o [3] = r.getString("biaya_bimbingan");
                o [4] = r.getString("cicilan_biaya");
                o [5] = r.getString("biaya_akhir");
                o [6] = r.getString("tanggal_pendaftaran");
                o [7] = r.getString("jam_pendaftaran");
            }
            r.close();
            s.close();
        }catch(SQLException e){
            System.out.println("terjadi kesalahan");
        }
    }
    
    public void clear()
    {
        txNama3.setText("");
        cbLama.setSelectedItem(null);
        txBiayaAwal.setText("");
        txCicilan.setText("");
        txBiayaAkhir.setText("");
    }
    
    private void updateTime() {
        // Format tanggal dan waktu
        SimpleDateFormat formatter = new SimpleDateFormat("EEEE, dd MMMM yyyy HH:mm:ss");
        String currentTime = formatter.format(new Date());
        // Set teks JLabel
         txTanggal.setText(currentTime);
    }
    
    /**
     * Creates new form FormPembayaran
     */
    public FormPembayaran() {
        initComponents();
        txId3.setEnabled(false);
        txNama3.setEnabled(false);
        txTanggal.setEnabled(false);
        txBiayaAwal.setEnabled(false);
        txBiayaAkhir.setEnabled(false);
        txArea.setEnabled(false);
        loadData();
        Timer timer = new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                updateTime();
            }
    });
           timer.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txId3 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txNama3 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cbLama = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txBiayaAwal = new javax.swing.JTextField();
        btnKonfirmasi3 = new javax.swing.JButton();
        btnBatal3 = new javax.swing.JButton();
        btnKeluar3 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txBiayaAkhir = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btnJumlah = new javax.swing.JButton();
        txCicilan = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txArea = new javax.swing.JTextArea();
        jLabel12 = new javax.swing.JLabel();
        btnGenerate = new javax.swing.JButton();
        btnPrint = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        txTanggal = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("ID PENDAFTAR:");

        jLabel2.setText("NAMA PENDAFTAR:");

        jLabel3.setText("LAMA BIMBINGAN:");

        cbLama.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        cbLama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbLamaActionPerformed(evt);
            }
        });

        jLabel4.setText("BULAN");

        jLabel5.setText("BIAYA AWAL  BIMBINGAN:");

        btnKonfirmasi3.setText("KONFIRMASI");
        btnKonfirmasi3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKonfirmasi3ActionPerformed(evt);
            }
        });

        btnBatal3.setText("BATAL");
        btnBatal3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatal3ActionPerformed(evt);
            }
        });

        btnKeluar3.setText("KELUAR");
        btnKeluar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluar3ActionPerformed(evt);
            }
        });

        jLabel6.setText("CICILAN BIAYA:");

        jLabel7.setText("BIAYA AKHIR BIMBINGAN:");

        jLabel8.setText("Rp. ");

        jLabel9.setText("Rp. ");

        jLabel10.setText("Rp. ");

        btnJumlah.setText("JUMLAHKAN");
        btnJumlah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJumlahActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(51, 204, 255));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("FORM PEMBAYARAN");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addGap(397, 397, 397))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        txArea.setColumns(20);
        txArea.setRows(5);
        txArea.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
                txAreaAncestorMoved(evt);
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane1.setViewportView(txArea);

        jLabel12.setText("PREVIEW PRINT");

        btnGenerate.setText("GENERATE PRINT");
        btnGenerate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerateActionPerformed(evt);
            }
        });

        btnPrint.setText("PRINT");
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });

        jLabel13.setText("TANGGAL & JAM:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnKonfirmasi3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBatal3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnGenerate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnPrint)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnKeluar3))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel10)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel9))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnJumlah)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(txBiayaAkhir)
                                                .addComponent(txBiayaAwal)
                                                .addComponent(txCicilan, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addComponent(txId3, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txNama3, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(cbLama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel4))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txTanggal)))
                        .addGap(64, 64, 64)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addGap(160, 160, 160))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txId3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txNama3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(cbLama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4))
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txBiayaAwal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel9)
                            .addComponent(txCicilan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txBiayaAkhir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnJumlah))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnKonfirmasi3)
                    .addComponent(btnBatal3)
                    .addComponent(btnKeluar3)
                    .addComponent(btnGenerate)
                    .addComponent(btnPrint))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnKonfirmasi3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKonfirmasi3ActionPerformed
        // TODO add your handling code here:
        String id = txId3.getText();
        String nama_pendaftar = txNama3.getText();
        String lama_bimbingan = (String)cbLama.getSelectedItem();
        String biaya_bimbingan = txBiayaAwal.getText();
        String cicilan_biaya = txCicilan.getText();
        String biaya_akhir = txBiayaAkhir.getText();
        String tanggal_pendaftaran = txTanggal.getText();
        try
        {
            Connection c = Koneksi.getKoneksi();
            String sql = "INSERT INTO biaya_bimbel_pendaftar VALUES (?, ?, ?, ?, ?, ?, ?)";
            PreparedStatement p = c.prepareStatement(sql);
            p.setString(1, id);
            p.setString(2, nama_pendaftar);
            p.setString(3, lama_bimbingan);
            p.setString(4, biaya_bimbingan);
            p.setString(5, cicilan_biaya);
            p.setString(6, biaya_akhir);
            p.setString(7, tanggal_pendaftaran);
            p.executeUpdate();
            p.close();
            JOptionPane.showMessageDialog(this, "Data Tersimpan" + "\n Mohon membawa berkas akte lahir, kartu keluarga, dan biaya cicilan saat verifikasi berkas ditempat" + "\n Mohon cek email anda secara berkala.");
            dispose();
            home FormEnam = new home();
            FormEnam.setVisible(true);
        }
        catch(SQLException e)
        {
            System.out.println("Terjadi Kesalahan");
        }
        finally
        {
        }
    }//GEN-LAST:event_btnKonfirmasi3ActionPerformed

    private void btnBatal3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatal3ActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_btnBatal3ActionPerformed

    private void btnKeluar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluar3ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnKeluar3ActionPerformed

    private void cbLamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbLamaActionPerformed
        // TODO add your handling code here:
        String itemSelected = (String)cbLama.getSelectedItem();
        int bayar = 100000;
        if("1".equals(itemSelected))
        {
            txBiayaAwal.setText("" + bayar);
        }
        else if("2".equals(itemSelected))
        {
            txBiayaAwal.setText("" + bayar * 2);
        }
        else if("3".equals(itemSelected))
        {
            txBiayaAwal.setText("" + bayar * 3);
        }
        else if("4".equals(itemSelected))
        {
            txBiayaAwal.setText("" + bayar * 4);
        }
        else if("5".equals(itemSelected))
        {
            txBiayaAwal.setText("" + bayar * 5);
        }
        else if("6".equals(itemSelected))
        {
            txBiayaAwal.setText("" + bayar * 6);
        }
        else if("7".equals(itemSelected))
        {
            txBiayaAwal.setText("" + bayar * 7);
        }
        else if("8".equals(itemSelected))
        {
            txBiayaAwal.setText("" + bayar * 8);
        }
        else if("9".equals(itemSelected))
        {
            txBiayaAwal.setText("" + bayar * 9);
        }
        else if("10".equals(itemSelected))
        {
            txBiayaAwal.setText("" + bayar * 10);
        }
        else if("11".equals(itemSelected))
        {
            txBiayaAwal.setText("" + bayar * 11);
        }
        else if("12".equals(itemSelected))
        {
            txBiayaAwal.setText("" + bayar * 12);
        }
    }//GEN-LAST:event_cbLamaActionPerformed

    private void btnJumlahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJumlahActionPerformed
          // TODO add your handling code here:
        int a = Integer.parseInt(txBiayaAwal.getText());
        int b = Integer.parseInt(txCicilan.getText());
        if (a > b)
        {
            int hasil = a-b;
            txBiayaAkhir.setText(Integer.toString(hasil));
        }
        else if (a < b)
        {
            txBiayaAkhir.setText("LUNAS");
        }
        else if(a == b)
        {
            txBiayaAkhir.setText("LUNAS");
        }
    }//GEN-LAST:event_btnJumlahActionPerformed

    private void txAreaAncestorMoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_txAreaAncestorMoved
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txAreaAncestorMoved

    private void btnGenerateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerateActionPerformed
        // TODO add your handling code here:
        txArea.setText("===================================================\n");
        txArea.setText(txArea.getText()+"                              FORM PEMBAYARAN BIMBINGAN\n");
        txArea.setText(txArea.getText()+"ID Pendaftar: " + txId3.getText() + "\n");
        txArea.setText(txArea.getText()+"Nama Pendaftar: " + txNama3.getText() + "\n");
        txArea.setText(txArea.getText()+"Lama Bimbingan: "+ cbLama.getSelectedItem() + " bulan\n");
        txArea.setText(txArea.getText()+"Biaya Awal Bimbingan: Rp "+txBiayaAwal.getText() + "\n");
        txArea.setText(txArea.getText()+"Biaya Cicilan Yang Dibayar: Rp " + txCicilan.getText() + "\n" );
        txArea.setText(txArea.getText()+"Biaya Akhir Cicilan: Rp " + txBiayaAkhir.getText() + "\n");
        txArea.setText(txArea.getText()+"Tanggal dan Jam Pendaftaran: "+txTanggal.getText());
        txArea.setText(txArea.getText()+"\n");
        txArea.setText(txArea.getText()+"\n");
        txArea.setText(txArea.getText()+"\n");
        txArea.setText(txArea.getText()+"Mohon membawa berkas akte lahir, kartu keluarga, dan biaya cicilan saat verifikasi." + "\n");
        txArea.setText(txArea.getText()+"Mohon cek email Anda secara berkala." + "\n");
    }//GEN-LAST:event_btnGenerateActionPerformed

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
        // TODO add your handling code here:
         try
        {
            txArea.print();
        }
        catch (Exception e)
        {

        }
    }//GEN-LAST:event_btnPrintActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPembayaran().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal3;
    private javax.swing.JButton btnGenerate;
    private javax.swing.JButton btnJumlah;
    private javax.swing.JButton btnKeluar3;
    private javax.swing.JButton btnKonfirmasi3;
    private javax.swing.JButton btnPrint;
    private javax.swing.JComboBox<String> cbLama;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txArea;
    private javax.swing.JTextField txBiayaAkhir;
    public javax.swing.JTextField txBiayaAwal;
    private javax.swing.JTextField txCicilan;
    public javax.swing.JTextField txId3;
    public javax.swing.JTextField txNama3;
    private javax.swing.JTextField txTanggal;
    // End of variables declaration//GEN-END:variables
}
